name: オンラインギャンブラー.com
favicon: null
layout_spectrum: 0.49394
typography_spectrum: 0.5753837856464088
title: オンライン　海外　ギャンブル　カジノ　スポーツ　賭け事　ブックメーカー
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aeabb4'
    - '#2c1811'
    - '#81563d'
    - '#c7d7ec'
  brandStrength: 0.5
  lightness: 0.35227750265039504
  saturation: 0.39578007790260017
  rhythmicContrast: 0.7797425261233002
purpose: []
